package com.unisage.backend.entity.enums;

/**
 * The 7 states of a {@code chat_model_verifications} job — plan.md "Verification lifecycle",
 * table "Trạng thái verification". This exact order is the single source of truth: the V16 CHECK
 * constraint, {@code contracts/verification-statuses.json} (generated by {@code ContractExportTest},
 * never hand-edited), and every downstream consumer (unisage-web's generated TypeScript union) must
 * match this enum, never the other way around. Only Java ever transitions a job between these
 * states — Python/Celery reacts to HTTP status codes from claim/result, not to this enum.
 */
public enum ChatModelVerificationStatus {
    /** Waiting for a verifier to claim it. Set by Java when the job is created. */
    QUEUED,
    /** Claimed by a verifier; has an active lease. Set by Java on claim. */
    RUNNING,
    /** Candidate applied to the row (promoted). Terminal. */
    SUCCEEDED,
    /** PERMANENT error, or ran out of attempts. Terminal. */
    FAILED,
    /**
     * Superseded by a newer candidate (credential edited/re-verified while this job was open), or
     * the promote compare-and-set lost the race. Never promotes, even with a valid lease token.
     * Terminal.
     */
    SUPERSEDED,
    /** The credential was soft-deleted while this job was still open. Terminal. */
    CANCELLED,
    /**
     * EMBEDDING candidate verified successfully but changes the vector identity of the currently
     * active index — plan.md "Embedding identity guard". Never auto-promoted. Terminal.
     */
    REINDEX_REQUIRED
}
