-- Baseline schema for Flyway, captured from the dev database as it stood BEFORE UNISAGE-56
-- (createdBy/updatedBy as plain varchar, no relation to users). Generated by dumping the schema
-- Hibernate ddl-auto=update produced from that pre-change entity code:
--   docker exec <postgres> pg_dump -U postgres -d assistant_DB \
--     --schema-only --no-owner --no-privileges --no-comments
-- Existing databases are tagged onto this version via spring.flyway.baseline-* (see
-- application.properties) instead of re-running it; a fresh database runs it as migration V1,
-- then V2 applies the createdBy/updatedBy -> User FK change from
-- docs/adr/0002-audit-fields-user-relation.md.

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.access_levels (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    description character varying(255),
    level integer NOT NULL
);

CREATE TABLE public.categories (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255)
);

CREATE TABLE public.chat_models (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    api_base_url character varying(255),
    api_key_encrypted text,
    error_count integer,
    last_error_at timestamp(6) without time zone,
    llm_model_name character varying(255),
    llm_provider character varying(255),
    max_rpm integer,
    model_source_ref character varying(255),
    priority integer,
    source_type character varying(20) DEFAULT 'CLOUD_API'::character varying,
    CONSTRAINT chat_models_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['CLOUD_API'::character varying, 'SELF_HOSTED'::character varying])::text[])))
);

CREATE TABLE public.conversations (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    deleted_at timestamp(6) without time zone,
    ip_address character varying(255),
    title character varying(255),
    user_id uuid
);

CREATE TABLE public.departments (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    deleted_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255) NOT NULL,
    parent_id uuid
);

CREATE TABLE public.documents (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    deleted_at timestamp(6) without time zone,
    file_type character varying(255) NOT NULL,
    is_public boolean,
    source_url character varying(255) NOT NULL,
    status character varying(255),
    title character varying(255) NOT NULL,
    version integer,
    category_id uuid,
    department_id uuid,
    ingested_by uuid,
    min_access_level_id uuid,
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'OUTDATED'::character varying])::text[])))
);

CREATE TABLE public.messages (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    citations jsonb,
    content text NOT NULL,
    metadata jsonb,
    retrieval_score real,
    role character varying(255),
    status character varying(255),
    chat_model_id uuid,
    conversation_id uuid NOT NULL,
    CONSTRAINT messages_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ASSISTANT'::character varying, 'SYSTEM'::character varying])::text[]))),
    CONSTRAINT messages_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'STREAMING'::character varying, 'COMPLETED'::character varying, 'ERROR'::character varying])::text[])))
);

CREATE TABLE public.permissions (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    access_level integer,
    description character varying(255),
    method character varying(10) NOT NULL,
    name character varying(100) NOT NULL,
    path character varying(255) NOT NULL,
    resource_type character varying(50) NOT NULL,
    CONSTRAINT permissions_method_check CHECK (((method)::text = ANY ((ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying, 'ALL'::character varying])::text[]))),
    CONSTRAINT permissions_resource_type_check CHECK (((resource_type)::text = ANY ((ARRAY['USER'::character varying, 'ROLE'::character varying, 'PERMISSION'::character varying, 'DEPARTMENT'::character varying, 'USER_DEPARTMENT_ACCESS'::character varying, 'DOCUMENT'::character varying, 'CATEGORY'::character varying, 'ACCESS_LEVEL'::character varying, 'CHAT_MODEL'::character varying, 'LLM_TRACE_LOG'::character varying, 'INGEST'::character varying, 'CONVERSATION'::character varying, 'MESSAGE'::character varying, 'AUDIT_LOG'::character varying, 'SYSTEM'::character varying, 'OTHER'::character varying])::text[])))
);

CREATE TABLE public.role_permissions (
    permission_id uuid NOT NULL,
    role_id uuid NOT NULL
);

CREATE TABLE public.roles (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    description character varying(255),
    is_system_role boolean,
    name character varying(255) NOT NULL
);

CREATE TABLE public.usage_limits (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    ip_address character varying(255),
    last_used_at timestamp(6) without time zone,
    limit_type character varying(255),
    scope character varying(255),
    scope_date date,
    used_count integer,
    user_id uuid,
    CONSTRAINT usage_limits_limit_type_check CHECK (((limit_type)::text = ANY ((ARRAY['MESSAGE'::character varying, 'TOKEN'::character varying, 'IMAGE'::character varying, 'API'::character varying])::text[]))),
    CONSTRAINT usage_limits_scope_check CHECK (((scope)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying])::text[])))
);

CREATE TABLE public.user_department_access (
    department_id uuid NOT NULL,
    user_id uuid NOT NULL,
    access_level integer
);

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_active boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    avatar_url character varying(255),
    code character varying(255),
    deleted_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    extra_info text,
    first_name character varying(255),
    gender character varying(255),
    last_login timestamp(6) without time zone,
    last_name character varying(255),
    password_hash character varying(255) NOT NULL,
    phone character varying(255),
    status character varying(255),
    access_level_id uuid,
    role_id uuid NOT NULL,
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BANNED'::character varying])::text[])))
);

ALTER TABLE ONLY public.access_levels
    ADD CONSTRAINT access_levels_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_models
    ADD CONSTRAINT chat_models_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (permission_id, role_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk71vrxovabe8x9tom8xwefi3e7 UNIQUE (code);

ALTER TABLE ONLY public.access_levels
    ADD CONSTRAINT uki0qxbo6swdr1m78rarji7bw3n UNIQUE (level);

ALTER TABLE ONLY public.usage_limits
    ADD CONSTRAINT uknt58510d4ug3o0vcfqtvn76do UNIQUE (ip_address, limit_type, scope, scope_date);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);

ALTER TABLE ONLY public.usage_limits
    ADD CONSTRAINT ukpjx2c41oahru2w34f98xlu79w UNIQUE (user_id, limit_type, scope, scope_date);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

ALTER TABLE ONLY public.usage_limits
    ADD CONSTRAINT usage_limits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_department_access
    ADD CONSTRAINT user_department_access_pkey PRIMARY KEY (department_id, user_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_permission_name ON public.permissions USING btree (name);

CREATE INDEX idx_permission_path_method ON public.permissions USING btree (path, method);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk1rm8m98c861dhhm81q18decoi FOREIGN KEY (min_access_level_id) REFERENCES public.access_levels(id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk2mmqmvab6bv1nhqgyy4aoyp8c FOREIGN KEY (ingested_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_department_access
    ADD CONSTRAINT fk3ya1d9udwe1i3qcf5v7k0vy1u FOREIGN KEY (department_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fk63q917a0aq92i7gcw6h7f1jrv FOREIGN KEY (parent_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk6i5021opajlb28u7khn6syiyy FOREIGN KEY (access_level_id) REFERENCES public.access_levels(id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk70g21yw6d0n958n3khscvgbls FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.user_department_access
    ADD CONSTRAINT fkcavdvxhh02xsgamwx1u0ncx59 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkhtlwf3e8ua3jcfko65antrpcy FOREIGN KEY (department_id) REFERENCES public.departments(id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkj9axgkoch0sdks9jpl3me7gji FOREIGN KEY (chat_model_id) REFERENCES public.chat_models(id);

ALTER TABLE ONLY public.usage_limits
    ADD CONSTRAINT fkj9yswsi9ld3vvulwptwbugek FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fkpltqvfcbkql9svdqwh0hw4g1d FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt492th6wsovh1nush5yl5jj8e FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);
